{{- if .Values.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.gateway.tlsSecretName }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  secretName: {{ .Values.gateway.tlsSecretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.hosts }}
    - {{ .host }}
    {{- end }}
{{- end }}
