apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: envoy-proxy
  namespace: envoy-gateway-system
spec:
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      labels:
        app: envoy-proxy
    spec:
      {{- if .Values.dedicatedNode.enabled }}
      nodeSelector:
        {{ .Values.dedicatedNode.key }}: {{ .Values.dedicatedNode.value }}
      tolerations:
        - key: {{ .Values.dedicatedNode.key }}
          operator: "Equal"
          value: {{ .Values.dedicatedNode.value }}
          effect: "NoSchedule"
      {{- end }}
      containers:
        - name: envoy
          image: {{ .Values.envoy.image }}
          args:
            - --config-path
            - /etc/envoy/bootstrap.yaml
          volumeMounts:
            - name: bootstrap
              mountPath: /etc/envoy/
      volumes:
        - name: bootstrap
          configMap:
            name: envoy-bootstrap