apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
  {{- if .Values.gateway.nodeSelector }}
  annotations:
    gateway.envoyproxy.io/infra: |-
      nodeSelector:
        {{- range $key, $value := .Values.gateway.nodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.gateway.tlsSecretName }}